# Generated by Django 5.0.6 on 2024-05-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
